### ISSUE TITLE
Barcode detector

### ISSUE THREAD

**Issue by yamila-fraiman** [a7med-mahmoud/react-native-ml-kit#6]
Hello, are you planning to add an image barcode parser?

**Comment by a7med-mahmoud** [comment]
Hey @yamila-fraiman! There's currently a PR (#3) by @s0rta to add barcode scanning, the PR needs some changes to be ready for merging. Hopefully it will be merged soon and we will have support for it.

**Comment by yamila-fraiman** [comment]
Could you estimate when? I need to implement it by the middle of June

**Comment by a7med-mahmoud** [comment]
Sorry, closed it by accident 😅.
I will try to make it happen by the end of May or so.

**Comment by a7med-mahmoud** [comment]
Now that the PR has been merged we have basic support for barcode scanning 🎉.
Check out the [README](https://github.com/a7med-mahmoud/react-native-ml-kit/tree/main/barcode-scanning) for instructions on how to use it.

**Comment by yamila-fraiman** [comment]
After installing barcode detector, i'm getting the following error when trying to use text-recognition. I think the error is related to different com.google.mlkit versions
implementation 'com.google.mlkit:face-detection:16.1.2'
implementation 'com.google.mlkit:barcode-scanning:17.0.2'
implementation 'com.google.mlkit:text-recognition:16.0.0-beta1'

Could you upgrade all to 17.0.2?

```
    java.lang.RuntimeException: Could not invoke TextRecognition.recognize
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:920) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/common/internal/Detector;
        at com.rnmlkit.textrecognition.TextRecognitionPackage.createNativeModules(TextRecognitionPackage.java:17)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1462)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1433)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1327)
        at com.facebook.react.ReactInstanceManager.access$1200(ReactInstanceManager.java:138)
```

**Comment by yamila-fraiman** [comment]
I upgraded the versions inside the lib build.gradle and now is working. Could you upgrade in your repo?

implementation 'com.google.mlkit:face-detection:16.1.5'
implementation 'com.google.mlkit:text-recognition:16.0.0-beta4'

**Comment by a7med-mahmoud** [comment]
I did upgrade all the native dependencies to latest in the latest versions of all the packages right now, can you try it out again?
